-- VHDL module instantiation generated by SCUBA ispLever_v51_SP2_Build (10)
-- Module  Version: 2.0
-- Wed Jun 28 10:02:03 2006

-- parameterized module component declaration
component FS_CLOCK_GEN
    port (CLK: in std_logic; RESET: in std_logic; CLKOP: out std_logic; 
        CLKOK: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : FS_CLOCK_GEN
    port map (CLK=>__, RESET=>__, CLKOP=>__, CLKOK=>__, LOCK=>__);

