-- VHDL module instantiation generated by SCUBA ispLever_v61_PROD_Build (37)
-- Module  Version: 3.2
-- Wed Nov 15 23:58:42 2006

-- parameterized module component declaration
component clockgen_main
    port (CLK: in std_logic; RESET: in std_logic; CLKOP: out std_logic; 
        CLKOK: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : clockgen_main
    port map (CLK=>__, RESET=>__, CLKOP=>__, CLKOK=>__, LOCK=>__);

