-- VHDL module instantiation generated by SCUBA ispLever_v60_PROD_Build (36)
-- Module  Version: 2.1
-- Thu Nov 30 04:15:48 2006

-- parameterized module component declaration
component FilterCell
    port (CLK0: in  std_logic; RST0: in  std_logic; 
        A0: in  std_logic_vector(8 downto 0); 
        A1: in  std_logic_vector(8 downto 0); 
        A2: in  std_logic_vector(8 downto 0); 
        A3: in  std_logic_vector(8 downto 0); 
        B0: in  std_logic_vector(8 downto 0); 
        B1: in  std_logic_vector(8 downto 0); 
        B2: in  std_logic_vector(8 downto 0); 
        B3: in  std_logic_vector(8 downto 0); 
        SUM: out  std_logic_vector(19 downto 0));
end component;

-- parameterized module component instance
__ : FilterCell
    port map (CLK0=>__, RST0=>__, A0(8 downto 0)=>__, A1(8 downto 0)=>__, 
        A2(8 downto 0)=>__, A3(8 downto 0)=>__, B0(8 downto 0)=>__, B1(8 downto 0)=>__, 
        B2(8 downto 0)=>__, B3(8 downto 0)=>__, SUM(19 downto 0)=>__);

